version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: hs_user
      POSTGRES_PASSWORD: hs_pass
      POSTGRES_DB: hs_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    env_file: ./backend/.env.example
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data: